### PR TITLE
Add plugin information block

### PR DESCRIPTION
**Pull request by webaware**
G'day, this adds the basic plugin information block. It helps identify _which_ Memcache(d) object cache is installed on a given website, and provides links to the author's website and the GitHub project. vis:

drop-ins

### CODE REVIEW

**Comment by tollmanz** [comment]
Thanks a lot! This is merged in. I merged it into develop so it doesn't look like it is merged here.

**Comment by tollmanz** [comment]
Turns out I have to remove this. See https://github.com/tollmanz/wordpress-pecl-memcached-object-cache/commit/67245f06057617192b72d6c44f24ba4545829253.

**Comment by webaware** [comment]
So symlink the drop-in from a subfolder inside the plugin folder. At least with a plugin header, it will be identifiable when installed.

**Comment by tollmanz** [comment]
Kinda ;) I've actually been in the middle of reworking the recommendation for how to install the plugin. Most of this work is nearing completion on the `develop` branch. The new workflow will use WordPress.org and WP CLI for super easy installation. It will be something like:
1. Install from wordpress.org or use WP CLI:
   
   ``` bash
   wp plugin install pecl-memcached-object-cache --activate
   ```
2. Symlink the plugin to the drop-in location:
   
   ``` bash
   wp mem install
   ```
3. Check your configuration:
   
   ``` bash
   wp mem check
   ```
   
   Sample output:
   
   ``` bash
   vagrant@vvv:/srv/www/wordpress-develop/src$ wp mem check
   +------------------------------------------------+--------+
   | Check                                          | Result |
   +------------------------------------------------+--------+
   | Memcached PECL extension                       | ✓      |
   | Connect to Memcached via PHP                   | ✓      |
   | Memcached available via CLI                    | ✓      |
   | Memcached available via `wp-config.php` config | ✖      |
   | Memcached stores content                       | ✓      |
   | `object-cache.php` exists                      | ✓      |
   | Object cache stores content                    | ✓      |
   +------------------------------------------------+--------+
   ```
4. Fix any issues

Feel free to check this out in the `develop` branch.

Your PR is great and it can be applied to the master branch, but since I am so close to getting the rest of this launched, I prefer to not introduce it at this time.

**Comment by webaware** [comment]
Love it, looks great. I'll leave you to it then :) (no time to check out `develop` right now, sadly; maybe late December)

**Pull request closed without merging**
