### PR TITLE
Memcached::get() expects parameter 2 to be a valid callback

### PR DESCRIPTION
**Pull request by tollmanz**
With php-fpm 5.5.3 and memcached 1.4.14 I'm seeing the following warning several times per request on WordPress 3.8.1:

```
PHP message: PHP Warning:  Memcached::get() expects parameter 2 to be a valid callback, no array or string given in /usr/share/wordpress/wp-content/object-cache.php on line 1262
```

### CODE REVIEW

**Comment by tollmanz** [comment]
Thanks for the report @Einkoro! I've tried to reproduce with a box running WordPress 3.8.1, PHP 5.5.8 and Memcached 1.4.15. I cannot reproduce this error. 

My hunch is that there is an error with how `wp_cached_get()` is being called somewhere. Can you do a stack trace so we can locate the code that initiates the call to `Memcached::get()`?

Because this library uses PECL Memcached, the `wp_cache_get()` function support 4 arguments. The `wp_cache_get()` function in core only uses the first two arguments. The extra 2 arguments are for advanced functionality that is only supported by this library. In other words, core code _should not be using that 3rd argument_ and thus, I think there must be some custom code that is using this code incorrectly.

Either way, the stack trace will help me to reproduce this and get to the bottom of this issue.

**Comment by einkoro** [comment]
My hunch is that Advanced Custom Fields is calling wp_cache_get().

I'll poke at later tonight when I get home and see what I kind find and provide a stack trace.

**Comment by tollmanz** [comment]
Ah...I found one instance in core where the 3rd argument is used. In **wp-cron.php:L37**, the following is called:

``` php
$value = wp_cache_get( 'doing_cron', 'transient', true );
```

This may be causing the issue. This is only called during cron requests. I'm not sure if this would explain your issue since this is during cron.

Additionally, I [specifically handle this situation](https://github.com/tollmanz/wordpress-memcached-backend/blob/master/object-cache.php#L307-L313) so it shouldn't give such an error.

**Comment by tollmanz** [comment]
> My hunch is that Advanced Custom Fields is calling wp_cache_get().

Cool! I can take a look at that too. I usually avoid this plugin :wink:

**Comment by einkoro** [comment]
It definitely adds overhead but it's about the only decent way I've found to provide clients the level of CMS like control they desire over content. Google brings up a report of the issue on their forum so it seems the most likely cause.

**Comment by einkoro** [comment]
Here is the link to the report on their forum:
http://support.advancedcustomfields.com/forums/topic/lots-of-warning-when-object-cache-is-used/

I'm just at the pub at the moment otherwise is jump on the stack trace.

**Comment by tollmanz** [comment]
Thanks for that information, @Einkoro! I can see what the issue is here. I am not sure what the best fix is at the moment.

The core `wp_get_cache()` function signature is:

``` php
wp_cache_get( $key, $group = '', $force = false, &$found = null )
```

When writing my cache, I opted to not support the last two arguments. I made this decision because the `$force` parameter is not respected in core and `&$found` is not used in core. It seemed almost like this was a badly deprecated piece of functionality. 

Given that ACF is using these parameters, it is clear that my decision making process needed to include thinking about how 3rd party code would utilize this API. My decision was actually further influenced by the 2 most popular object caches, [Memcached Object Cache](http://plugins.svn.wordpress.org/memcached/trunk/object-cache.php) and [APC Object Cache](http://plugins.svn.wordpress.org/apc/trunk/object-cache.php), support `$force`, but do not support `&found`. Interestingly, I decided to not support `$force` because doing so would _result in different behavior than what core prescribes_. I then decided to not support `&$found` because these two, very popular and widely used backends, did not support it. 

What really has me concerned is that the APIs for these drop-ins and core are badly out of sync. I certainly can try to fix it in this library, but there would be disparity in all of these supposedly interchangeable libraries.

What I think I'll do in the short term is detect the type of the third argument. If it is not a string or array, it'll be set to null. The only valid value is string or array, so I'll just reject it if needed. For example, if you replace `wp_cache_get()` with the following, it should fix your problem:

``` php
function wp_cache_get( $key, $group = '', $cache_cb = null, &$cas_token = null ) {
    global $wp_object_cache;

    /**
     * Handles situations where the $force argument for the wp_cache_get function in core may be used. It is only
     * used once in all of WP Core and since the function does not do anything with it, it is pointless to support.
     * I'm catching the issue here to avoid conflicts.
     */
    if ( ! is_string( $cache_cb ) && ! is_array( $cache_cb ) )
        $cache_cb = null;

    if ( func_num_args() > 2 )
        return $wp_object_cache->get( $key, $group, '', false, $cache_cb, $cas_token );
    else
        return $wp_object_cache->get( $key, $group );
}
```

I'd also recommend that ACF patches this code. Technically, they are using the API correctly; however, if anyone uses one of the more popular object caches, unexpected behavior may result. Support for the `&$found` variable is sparse, so it really should not be relied upon. 

Again, this is just a patch for now. I am not entirely certain what I want to do long-term. I probably should just support the two arguments that I previously did not support.

**Comment by tollmanz** [comment]
In [20004](https://core.trac.wordpress.org/ticket/20004), `&$found` was added in a back-compat manner to easily check if the value was found. Other backends are lagging behind and not supporting the value. This suggests that `&$found` should _definitely be supported_.

Looking at this again, I think that `$force` and `&$found` need to be supported. The other libraries are supporting `$force` even though core does not and perhaps this parameter is only intended for 3rd party caches.  `&$found` should be supported for reasons enumerated above.

**Comment by tollmanz** [comment]
[W3TC](http://plugins.svn.wordpress.org/w3-total-cache/trunk/wp-content/object-cache.php) also does not support `$force` or `&$found`. Yeesh...this is crazy how divergent everything is.

**Comment by tollmanz** [comment]
ACF uses the following code that causes this problem:

``` php
// cache
$found = false;
$cache = wp_cache_get( 'field_groups', 'acf', false, $found );

if( $found )
{
    return $cache;
}
```

The only time that this code will work is when a 3rd party object cache is not used. Since I cannot find a 3rd party cache that supports `&$found`, `$found` will always be false.

**Comment by tollmanz** [comment]
Yet another important reason to support the `$force` parameter: https://core.trac.wordpress.org/ticket/17462. The cron lock depends on the persistent cache forcing the lookup.

**Comment by tollmanz** [comment]
I've changed this to a pull request so I can begin work on a fix.

**Comment by tollmanz** [comment]
@Einkoro I'm pretty happy with the fix that I implemented. Would you mind checking to see if the `get-fix` branch resolves your issue?

**Comment by einkoro** [comment]
No more warnings with the get-fix branch on my end.

**Comment by tollmanz** [comment]
:boom: Thanks!

**Comment by tollmanz** [comment]
Thanks again for reporting this issue. It's all merged now. I'm not going to support the `$false` argument for now. I think it's a terribly implemented argument and I do not think it will be important to support.

**Pull request merged**
