### PR TITLE
Expiry Times

### PR DESCRIPTION
**Pull request by tollmanz**
To handle expiry times over 30 days, +time() needs to be added to the expiry when setting it in $this->m->add...

I think it should be handled in this drop-in because APC and other cache handlers do not have this limitation. Therefore adding time() in a theme/plugin when using wp_set_cache() would add ~44 years to all expiries on other cache systems.

Fortunately you can add time() to expiries that are any length because it's meant to handle them all, event time()+0 would work fine. so a blanket fix can be applied.

I'll try to find the time() to make a pull request.

Read more: http://www.php.net/manual/en/memcached.expiration.php

### CODE REVIEW

**Comment by tollmanz** [comment]
Thanks gents for sticking with this! @mbijon This has totally clicked now (probably helps that I have time to actually think about it :smile: ).

I have converted this to a PR and added initial tests that document the breakage that you indicated. Sure enough 30 days is cached appropriately and 30 days + 1 second is immediately expired. Now that we have the unit test, the fix should be straight forwardish.

**Comment by tollmanz** [comment]
Need to add unit tests for:
- [x] CAS expirations
- [x] Set multi expirations

The fix for this will be to add a method that "cleans" the expiration time. If greater than 30 dates, it'll be converted to a timestamp, otherwise, it'll be left alone.

**Comment by tollmanz** [comment]
I implemented this fix by inspecting the expiration value. If it is greater than 30 days in seconds and less than the current timestamp, the value is converted to a timestamp. If it is greater than timestamp, then it's just assumed to be a timestamp. If someone's app depends on the distinction between a 44.5 and 45 year cache expiration value, I'll happily take the blame for breaking the app.

**Comment by mbijon** [comment]
+1

Bonus points if you add the distinction between 44.5 and 45-year caches to the plugin docs ;)

**Comment by tollmanz** [comment]
We've dealt with this issue, but should be noted that this is a PECL Memcached bug: https://github.com/php-memcached-dev/php-memcached/issues/142.

**Comment by mbijon** [comment]
A bug from 2009, wow.

I'd thought this behavior was by design it's been in there so long.

**Pull request merged**
