### PR TITLE
Publish this plugin in wordpress.org

### PR DESCRIPTION
**Pull request by tollmanz**

### CODE REVIEW

**Comment by tollmanz** [comment]
I'm working to get this on WordPress.org. The toughest part of this transition is naming the plugin. The [WordPress Memcached Object Cache](https://wordpress.org/plugins/memcached/) plugin exists and would be the obvious name for the plugin. Ideally, I want there to be some clarity about what you get with one plugin over the other. While most of this distinction needs to be handled in the description, it would be nice to get the process started in the title.

Just to be clear, the difference is that the other plugin uses PECL Memcache as the Memcached interface, whereas this plugin uses PECL Memcached as the Memcached interface. Ugh, right?

I'm thinking of _PECL Memcached Object Cache_. Any thoughts on this?

**Comment by rclilly** [comment]
Zack, what distinguishes this plugin from Boren's, other than memcache vs. memcached? What advantages does memcached offer over memcache? If you can articulate the main distinction(s), and then sum that up in one or two words, you could then use those as part of the title.

**Comment by westonruter** [comment]
What about, “The Other Memcache Object Cache” plugin?

**Comment by tollmanz** [comment]
> what distinguishes this plugin

PECL Memcached distinguishes the plugin. I'm thinking PECL Memcached Object Cache makes a lot of sense.

> What about, “The Other Memcache Object Cache” plugin?

:wink:

**Comment by tollmanz** [comment]
The code changes for this is done. I still need to deploy to WordPress.org, but need to get a few things in order before doing so. This branch is merged into the `develop` branch and ready for merge into `master` once the first release is ready. I'm closing this now because the work is essentially done.

**Comment by rclilly** [comment]
Just to be painfully obvious, would it help to spell it "PECL MemcacheD Object Cache" (note the uppercase D) since that's the differentiator? The other one is PECL as well, but doesn't have the D. ;-) Then, in the plugin's description you can state the main advantages of memcached over memcache, and perhaps provide a link to your existing writing on the topic.

**Comment by tollmanz** [comment]
> Just to be painfully obvious, would it help to spell it "PECL MemcacheD Object Cache" (note the uppercase D) since that's the differentiator?

It might be, but that is ugly ;) I think I might prefer to leave the painfully obvious pieces in the description.

**Comment by rclilly** [comment]
On Tue, Jul 29, 2014 at 8:55 PM, Zack Tollman notifications@github.com
wrote:

> Just to be painfully obvious, would it help to spell it "PECL MemcacheD
> Object Cache" (note the uppercase D) since that's the differentiator?
> 
> It might be, but that is ugly ;) I think I might prefer to leave the
> painfully obvious pieces in the description.

:+1: 

r

**Pull request closed without merging**
